django07_pjt/urls.py
from django.conf import settings
from django.conf.urls import include, url  # For django versions before 2.0
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/edit', views.update, name='update'),
    path('<int:movie_pk>/delete', views.delete, name='delete'),
    path('<int:movie_pk>/scores/new', views.scores_new, name='scores_new'),
    # path('<int:movie_pk>/scores/<int:rates_pk>/delete', views.scores_delete, name='scores_delete'),  
]

movies/models.py
from django.db import models

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    
class Score(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

movies/forms.py
from django import forms 
from .models import Movie, Score

class MovieForm(forms.ModelForm):
    class Meta: 
        model = Movie
        fields = '__all__'

class ScoreForm(forms.ModelForm):
    class Meta: 
        model = Score
        fields = ['content', 'score']

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Avg
from .models import Genre, Movie, Score
from .forms import MovieForm, ScoreForm

# Create your views here.
def index(request):
    movies = Movie.objects.annotate(score_avg=Avg('score__score')).all()
    context = {'movies': movies}
    return render(request, 'movies/index.html', context)

def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {'form': form}
    return render(request, 'movies/form.html', context)

def detail(request, movie_pk):
    # 1. annotate 활용하여 추가 칼럼을 score_avg를 score의 score 평균으로 설정. 
    # template에서는 movie.score_avg로 활용할 것.
    # 쿼리 2 
    movie = get_object_or_404(Movie.objects.annotate(score_avg=Avg('score__score')), pk=movie_pk)
    scores = movie.score_set.all()
    form = ScoreForm()
    context = {'movie': movie, 'scores': scores, 'form': form}

    # 2. 설명하기는 좋을지 모르지만..
    # template에서는 score_avg로 활/용할 것.
    # 쿼리 3
    # movie = Movie.objects.get(pk=movie_pk)
    # scores = movie.score_set.all()
    # score_avg = movie.score_set.aggregate(Avg('score')).get('score__avg')
    # context = {'movie': movie, 'scores': scores, 'score_avg': score_avg}

    return render(request, 'movies/detail.html', context)
    

def update(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {'form': form}
    return render(request, 'movies/form.html', context)

def delete(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    movie.delete()
    return redirect('movies:detail', movie_pk)

def scores_new(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        '''
        방법 1. 
        form = ScoreForm(request.POST)
        if form.is_valid():
            score = form.save(commit=False)
            score.movie = movie
            score.save()
        '''
        # 방법 2.
        score = Score(movie=movie)
        form = ScoreForm(request.POST, instance=score)
        if form.is_valid():
            score = form.save()
            return redirect('movies:detail', movie.pk)

    return redirect('movies:detail', movie_pk) 
    ''' 
    # 굳이 오류 메세지 보여주고싶다면, 중복 코드밖에 생각 안나네여.
    # movie = Movie.objects.annotate(score_avg=Avg('score__score')).get(pk=movie_pk)
    # scores = movie.score_set.all()
    # context = {'movie': movie, 'scores': scores, 'form': form}
    # return render(request, 'movies/detail.html', context)
    '''

movies/templates/movies/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{ movie.title }}</h1>
    <p>{{movie.genre.name}}</p>
    <p>{{movie.description}}</p>
    <hr>
    <form action="{% url 'movies:scores_new' movie.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }} 
        <input type="submit">
    </form>
    <p>{{ movie.score_avg }}</p>
    {% for score in scores %}
    <p>{{score.content}}</p>
    <p>{{score.score}}</p>
    <hr>
    {% endfor %}
</body>
</html>

movies/templates/movies/form.html
{% if request.resolver_match.url_name == 'create' %}
    <h1>영화 등록하기</h1>
{% else %}
    <h1>영화 수정하기</h1>
{% endif %}

<form method="POST"> 
    {% csrf_token %} 
    {{ form.as_p }} 
    <input type="submit" value="Submit"> 
</form>

movies/templates/movies/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% for movie in movies %}
    <p><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></p>
    <p>{{ movie.score_avg }}</p>
    <img src="{{movie.poster_url}}">
    <hr>
    {% endfor %}
</body>
</html>